import type { Product } from "../types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Яблуко",
    unit: "g", // латиница
    source: "OpenFoodFacts", // строго по типу
    nutrients: {
      calories: 52,
      protein: 0.3,
      fat: 0.2,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      transFat: 0,
      cholesterol: 0,
      carbs: 14,
      sugars: 0,
      fiber: 0,
      sodium: 0,
      potassium: 0,
      vitaminA: 0,
      vitaminB: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminE: 0,
      vitaminK: 0,
      calcium: 0,
      iron: 0,
      magnesium: 0,
      zinc: 0,
      phosphorus: 0,
    },
  },
  {
    id: "2",
    name: "Молоко",
    unit: "ml",
    source: "OpenFoodFacts",
    nutrients: {
      calories: 42,
      protein: 3.4,
      fat: 1,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      transFat: 0,
      cholesterol: 0,
      carbs: 5,
      sugars: 0,
      fiber: 0,
      sodium: 0,
      potassium: 0,
      vitaminA: 0,
      vitaminB: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminE: 0,
      vitaminK: 0,
      calcium: 0,
      iron: 0,
      magnesium: 0,
      zinc: 0,
      phosphorus: 0,
    },
  },
  {
    id: "3",
    name: "Куряче філе",
    unit: "g",
    source: "OpenFoodFacts",
    nutrients: {
      calories: 165,
      protein: 31,
      fat: 3.6,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      transFat: 0,
      cholesterol: 0,
      carbs: 0,
      sugars: 0,
      fiber: 0,
      sodium: 0,
      potassium: 0,
      vitaminA: 0,
      vitaminB: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminE: 0,
      vitaminK: 0,
      calcium: 0,
      iron: 0,
      magnesium: 0,
      zinc: 0,
      phosphorus: 0,
    },
  },
  {
    id: "4",
    name: "Банан",
    unit: "g",
    source: "OpenFoodFacts",
    nutrients: {
      calories: 89,
      protein: 1.1,
      fat: 0.3,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      transFat: 0,
      cholesterol: 0,
      carbs: 23,
      sugars: 0,
      fiber: 0,
      sodium: 0,
      potassium: 0,
      vitaminA: 0,
      vitaminB: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminE: 0,
      vitaminK: 0,
      calcium: 0,
      iron: 0,
      magnesium: 0,
      zinc: 0,
      phosphorus: 0,
    },
  },
  {
    id: "5",
    name: "Олія оливкова",
    unit: "ml",
    source: "OpenFoodFacts",
    nutrients: {
      calories: 884,
      protein: 0,
      fat: 100,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      transFat: 0,
      cholesterol: 0,
      carbs: 0,
      sugars: 0,
      fiber: 0,
      sodium: 0,
      potassium: 0,
      vitaminA: 0,
      vitaminB: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminE: 0,
      vitaminK: 0,
      calcium: 0,
      iron: 0,
      magnesium: 0,
      zinc: 0,
      phosphorus: 0,
    },
  },
  {
    id: "6",
    name: "Вівсянка",
    unit: "g",
    source: "OpenFoodFacts",
    nutrients: {
      calories: 389,
      protein: 17,
      fat: 7,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      transFat: 0,
      cholesterol: 0,
      carbs: 66,
      sugars: 0,
      fiber: 0,
      sodium: 0,
      potassium: 0,
      vitaminA: 0,
      vitaminB: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminE: 0,
      vitaminK: 0,
      calcium: 0,
      iron: 0,
      magnesium: 0,
      zinc: 0,
      phosphorus: 0,
    },
  },
];
