import type { Product } from "../types/product";

const baseNutrients = {
  saturatedFat: 0,
  polyunsaturatedFat: 0,
  transFat: 0,
  cholesterol: 0,
  sugars: 0,
  fiber: 0,
  sodium: 0,
  potassium: 0,
  vitaminA: 0,
  vitaminB: 0,
  vitaminC: 0,
  vitaminD: 0,
  vitaminE: 0,
  vitaminK: 0,
  calcium: 0,
  iron: 0,
  magnesium: 0,
  zinc: 0,
  phosphorus: 0,
};

export const mockProducts: Product[] = [
  {
    id: "manual-oats",
    name: "Вівсянка",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 389, protein: 17, fat: 7, carbs: 66, ...baseNutrients },
  },
  {
    id: "manual-greek-yogurt",
    name: "Грецький йогурт",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 73, protein: 10, fat: 2, carbs: 3.9, ...baseNutrients },
  },
  {
    id: "manual-banana",
    name: "Банан",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 89, protein: 1.1, fat: 0.3, carbs: 23, ...baseNutrients },
  },
  {
    id: "manual-egg-boiled",
    name: "Яйце варене",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 155, protein: 13, fat: 11, carbs: 1.1, ...baseNutrients },
  },
  {
    id: "manual-egg-fried",
    name: "Яйце смажене",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 196, protein: 14, fat: 15, carbs: 1, ...baseNutrients },
  },
  {
    id: "manual-chicken",
    name: "Куряче філе",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 165, protein: 31, fat: 3.6, carbs: 0, ...baseNutrients },
  },
  {
    id: "manual-turkey",
    name: "Індичка",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 135, protein: 29, fat: 1.5, carbs: 0, ...baseNutrients },
  },
  {
    id: "manual-beef",
    name: "Яловичина",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 187, protein: 26, fat: 9, carbs: 0, ...baseNutrients },
  },
  {
    id: "manual-cheese",
    name: "Сир твердий",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 356, protein: 25, fat: 27, carbs: 2, ...baseNutrients },
  },
  {
    id: "manual-cottage-cheese",
    name: "Сир кисломолочний",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 121, protein: 17, fat: 5, carbs: 3, ...baseNutrients },
  },
  {
    id: "manual-tomato",
    name: "Помідор",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 18, protein: 0.9, fat: 0.2, carbs: 3.9, ...baseNutrients },
  },
  {
    id: "manual-cucumber",
    name: "Огірок",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 15, protein: 0.7, fat: 0.1, carbs: 3.6, ...baseNutrients },
  },
  {
    id: "manual-avocado",
    name: "Авокадо",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 160, protein: 2, fat: 15, carbs: 9, ...baseNutrients },
  },
  {
    id: "manual-rice",
    name: "Рис варений",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 130, protein: 2.7, fat: 0.3, carbs: 28, ...baseNutrients },
  },
  {
    id: "manual-buckwheat",
    name: "Гречка варена",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 110, protein: 4.2, fat: 1.1, carbs: 21.3, ...baseNutrients },
  },
  {
    id: "manual-salmon",
    name: "Лосось",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 208, protein: 20, fat: 13, carbs: 0, ...baseNutrients },
  },
  {
    id: "manual-nuts",
    name: "Мигдаль",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 579, protein: 21, fat: 50, carbs: 22, ...baseNutrients },
  },
  {
    id: "manual-apple",
    name: "Яблуко",
    unit: "g",
    source: "Manual",
    nutrients: { calories: 52, protein: 0.3, fat: 0.2, carbs: 14, ...baseNutrients },
  },
];
