export const accountCopy = {
  uk: {
    title: "Акаунт і дані",
    subtitle:
      "Експортуйте свої дані, перевіряйте, де вони зберігаються, і за потреби повністю видаляйте акаунт.",
    provider: "Дані",
    session: "Вхід",
    sync: "Синхронізація",
    security: "Безпека",
    providerRemote: "Хмарний профіль",
    sessionRemote: "Захищена сесія",
    securityRemote: "Вхід перевіряється сервером.",
    exportAction: "Експортувати мої дані",
    exportBusy: "Готуємо експорт...",
    exportSuccess: "Експорт даних готовий.",
    exportError: "Не вдалося створити експорт.",
    backupsTitle: "Резервні копії",
    backupsSubtitle:
      "Останні хмарні точки відновлення, створені після синхронізації даних.",
    backupsEmpty: "Резервні копії поки недоступні.",
    backupsLoading: "Завантажуємо резервні копії...",
    backupDownload: "Завантажити резервну копію",
    backupBusy: "Завантаження...",
    backupError: "Не вдалося завантажити резервну копію.",
    deleteAction: "Видалити акаунт",
    revokeAction: "Вийти з усіх сесій",
    revokeBusy: "Скасовуємо сесії...",
    revokeSuccess: "Усі сесії було завершено.",
    revokeError: "Не вдалося завершити всі сесії.",
    deleteBusy: "Видалення...",
    deleteSuccess: "Акаунт видалено.",
    deleteError: "Не вдалося видалити акаунт.",
    remoteNotice:
      "Дані профілю, харчування, води й налаштувань зберігаються в хмарі та відновлюються після входу на іншому пристрої.",
    confirmTitle: "Видалити цей акаунт?",
    confirmBody:
      "Це видалить акаунт, сесію, дані профілю, історію прийомів їжі, збережені продукти, шаблони й пам'ять штрихкодів для цієї інсталяції.",
    confirmCancel: "Скасувати",
    confirmDelete: "Так, видалити все",
    syncRemote: "Хмарна синхронізація активна",
    telegramTitle: "Telegram-помічник",
    telegramSubtitle:
      "Підключіть помічника, щоб отримувати нагадування, підказки та майбутні повідомлення асистента в Telegram.",
    telegramConnected: "Підключено",
    telegramDisconnected: "Не підключено",
    telegramUnavailable: "Telegram-помічник тимчасово недоступний.",
    telegramLoading: "Перевіряємо Telegram...",
    telegramConnect: "Підключити Telegram",
    telegramConnecting: "Готуємо посилання...",
    telegramDisconnect: "Відключити",
    telegramDisconnecting: "Відключаємо...",
    telegramConnectPending: "Відкрили Telegram. Завершіть підключення в помічнику.",
    telegramConnectError: "Не вдалося створити посилання Telegram.",
    telegramDisconnectSuccess: "Telegram відключено.",
    telegramDisconnectError: "Не вдалося відключити Telegram.",
    telegramBot: "Помічник",
    telegramConnectInstruction:
      "Якщо Telegram не відкрився автоматично, натисніть персональне посилання нижче. Звичайний /start без цього посилання не підключає акаунт.",
    telegramOpenPersonalLink: "Відкрити персональне посилання",
    telegramCopyLink: "Скопіювати посилання",
    telegramCopySuccess: "Посилання Telegram скопійовано.",
  },
  pl: {
    title: "Konto i dane",
    subtitle:
      "Eksportuj swoje dane, sprawdzaj, gdzie są zapisane, i w razie potrzeby usuń konto całkowicie.",
    provider: "Dane",
    session: "Sesja",
    sync: "Synchronizacja",
    security: "Bezpieczeństwo",
    providerRemote: "Profil w chmurze",
    sessionRemote: "Chroniona sesja",
    securityRemote: "Logowanie jest weryfikowane po stronie serwera.",
    exportAction: "Eksportuj moje dane",
    exportBusy: "Przygotowujemy eksport...",
    exportSuccess: "Eksport danych jest gotowy.",
    exportError: "Nie udało się utworzyć eksportu.",
    backupsTitle: "Kopie zapasowe",
    backupsSubtitle:
      "Ostatnie punkty przywracania w chmurze utworzone po synchronizacji danych.",
    backupsEmpty: "Kopie zapasowe nie są jeszcze dostępne.",
    backupsLoading: "Ładujemy kopie zapasowe...",
    backupDownload: "Pobierz kopię zapasową",
    backupBusy: "Pobieranie...",
    backupError: "Nie udało się pobrać kopii zapasowej.",
    deleteAction: "Usuń konto",
    revokeAction: "Wyloguj wszystkie sesje",
    revokeBusy: "Wycofywanie sesji...",
    revokeSuccess: "Wszystkie sesje zostały zakończone.",
    revokeError: "Nie udało się zakończyć wszystkich sesji.",
    deleteBusy: "Usuwanie...",
    deleteSuccess: "Konto zostało usunięte.",
    deleteError: "Nie udało się usunąć konta.",
    remoteNotice:
      "Dane profilu, jedzenia, wody i ustawień są przechowywane w chmurze i wracają po zalogowaniu na innym urządzeniu.",
    confirmTitle: "Usunąć to konto?",
    confirmBody:
      "To usunie konto, sesje, dane profilu, historię posiłków, zapisane produkty, szablony i pamięć kodów kreskowych dla tej instalacji.",
    confirmCancel: "Anuluj",
    confirmDelete: "Tak, usuń wszystko",
    syncRemote: "Synchronizacja z chmurą aktywna",
    telegramTitle: "Asystent Telegram",
    telegramSubtitle:
      "Podłącz asystenta, aby dostawać przypomnienia, wskazówki i przyszłe wiadomości w Telegramie.",
    telegramConnected: "Połączono",
    telegramDisconnected: "Nie połączono",
    telegramUnavailable: "Asystent Telegram jest chwilowo niedostępny.",
    telegramLoading: "Sprawdzamy Telegram...",
    telegramConnect: "Podłącz Telegram",
    telegramConnecting: "Przygotowujemy link...",
    telegramDisconnect: "Odłącz",
    telegramDisconnecting: "Odłączanie...",
    telegramConnectPending: "Otworzyliśmy Telegram. Dokończ połączenie w asystencie.",
    telegramConnectError: "Nie udało się utworzyć linku Telegram.",
    telegramDisconnectSuccess: "Telegram odłączony.",
    telegramDisconnectError: "Nie udało się odłączyć Telegram.",
    telegramBot: "Asystent",
    telegramConnectInstruction:
      "Jeśli Telegram nie otworzył się automatycznie, naciśnij osobisty link poniżej. Zwykłe /start bez tego linku nie połączy konta.",
    telegramOpenPersonalLink: "Otwórz osobisty link",
    telegramCopyLink: "Skopiuj link",
    telegramCopySuccess: "Link Telegram skopiowany.",
  },
  en: {
    title: "Account and data",
    subtitle:
      "Export your data, check where it is stored, and fully delete the account if needed.",
    provider: "Data",
    session: "Session",
    sync: "Sync",
    security: "Security",
    providerRemote: "Cloud profile",
    sessionRemote: "Protected session",
    securityRemote:
      "Sign-in is verified by the server.",
    exportAction: "Export my data",
    exportBusy: "Preparing export...",
    exportSuccess: "Data export is ready.",
    exportError: "Could not create export.",
    backupsTitle: "Backup copies",
    backupsSubtitle:
      "Latest cloud restore points created after synchronized data changes.",
    backupsEmpty: "Backup copies are not available yet.",
    backupsLoading: "Loading backup copies...",
    backupDownload: "Download backup",
    backupBusy: "Downloading...",
    backupError: "Could not download backup.",
    deleteAction: "Delete account",
    revokeAction: "Log out all sessions",
    revokeBusy: "Revoking sessions...",
    revokeSuccess: "All sessions were ended.",
    revokeError: "Could not end all sessions.",
    deleteBusy: "Deleting...",
    deleteSuccess: "Account deleted.",
    deleteError: "Could not delete account.",
    remoteNotice:
      "Your profile, meals, water, and settings are stored in the cloud and restored when you sign in on another device.",
    confirmTitle: "Delete this account?",
    confirmBody:
      "This will delete the account, session, profile data, meal history, saved products, templates, and barcode memory for this installation.",
    confirmCancel: "Cancel",
    confirmDelete: "Yes, delete everything",
    syncRemote: "Cloud sync is active",
    telegramTitle: "Telegram assistant",
    telegramSubtitle:
      "Connect the assistant to receive reminders, nudges, and future assistant messages in Telegram.",
    telegramConnected: "Connected",
    telegramDisconnected: "Not connected",
    telegramUnavailable: "Telegram assistant is temporarily unavailable.",
    telegramLoading: "Checking Telegram...",
    telegramConnect: "Connect Telegram",
    telegramConnecting: "Preparing link...",
    telegramDisconnect: "Disconnect",
    telegramDisconnecting: "Disconnecting...",
    telegramConnectPending: "Telegram opened. Finish connecting with the assistant.",
    telegramConnectError: "Could not create Telegram link.",
    telegramDisconnectSuccess: "Telegram disconnected.",
    telegramDisconnectError: "Could not disconnect Telegram.",
    telegramBot: "Assistant",
    telegramConnectInstruction:
      "If Telegram did not open automatically, use the personal link below. Plain /start without this link cannot connect your account.",
    telegramOpenPersonalLink: "Open personal link",
    telegramCopyLink: "Copy link",
    telegramCopySuccess: "Telegram link copied.",
  },
} as const;
