export const navigation = {
  uk: {
    dashboard: "Головна",
    food: "Їжа",
    recipes: "Рецепти",
    community: "Спільнота",
    progress: "Прогрес",
    womenHealth: "Ритм",
    coach: "Помічник",
    profile: "Профіль",
    admin: "Адмін",
    primaryAria: "Основна навігація",
    mobileAria: "Мобільна навігація",
    mobilePrimaryAria: "Основна мобільна навігація",
    languageAria: "Перемкнути мову",
    themeLight: "Світла тема",
    themeDark: "Темна тема",
    switchToLight: "Увімкнути світлу тему",
    switchToDark: "Увімкнути темну тему",
    brandHome: "На головну",
    accountSettings: "Налаштування акаунта",
  },
  pl: {
    dashboard: "Główna",
    food: "Jedzenie",
    recipes: "Przepisy",
    community: "Społeczność",
    progress: "Postępy",
    womenHealth: "Rytm",
    coach: "Asystent",
    profile: "Profil",
    admin: "Admin",
    primaryAria: "Główna nawigacja",
    mobileAria: "Nawigacja mobilna",
    mobilePrimaryAria: "Główna nawigacja mobilna",
    languageAria: "Zmień język",
    themeLight: "Jasny motyw",
    themeDark: "Ciemny motyw",
    switchToLight: "Włącz jasny motyw",
    switchToDark: "Włącz ciemny motyw",
    brandHome: "Do strony głównej",
    accountSettings: "Ustawienia konta",
  },
  en: {
    dashboard: "Home",
    food: "Food",
    recipes: "Recipes",
    community: "Community",
    progress: "Progress",
    womenHealth: "Rhythm",
    coach: "Assistant",
    profile: "Profile",
    admin: "Admin",
    primaryAria: "Primary navigation",
    mobileAria: "Mobile navigation",
    mobilePrimaryAria: "Mobile primary navigation",
    languageAria: "Switch language",
    themeLight: "Light theme",
    themeDark: "Dark theme",
    switchToLight: "Switch to light theme",
    switchToDark: "Switch to dark theme",
    brandHome: "Go home",
    accountSettings: "Account settings",
  },
} as const;
