export const createAuthRepository = (storage) => ({
  findUserByEmail: (email) => storage.findUserByEmail(email),
  findUserById: (userId) => storage.findUserById(userId),
  hasUserWithRole: (role) => storage.hasUserWithRole(role),
  insertUser: (user) => storage.insertUser(user),
  updateUser: (user) => storage.updateUser(user),
  updateUserRole: (payload) => storage.updateUserRole(payload),
  listUsers: () => storage.listUsers(),
  promoteUserByEmailToSuperAdmin: (email) => storage.promoteUserByEmailToSuperAdmin(email),
  deleteUser: (userId) => storage.deleteUser(userId),
  listUserBackups: (userId) => storage.listUserBackups(userId),
  readUserBackup: (userId, backupId) => storage.readUserBackup(userId, backupId),
  createAuditLog: (entry) => storage.createAuditLog(entry),
  listAuditLogs: (limit) => storage.listAuditLogs(limit),
  createSession: (session) => storage.createSession(session),
  findSessionByToken: (token) => storage.findSessionByToken(token),
  deleteSessionByToken: (token) => storage.deleteSessionByToken(token),
  deleteSessionsByUserId: (userId) => storage.deleteSessionsByUserId(userId),
  getLoginAttempt: (email) => storage.getLoginAttempt(email),
  upsertLoginAttempt: (attempt) => storage.upsertLoginAttempt(attempt),
  clearLoginAttempt: (email) => storage.clearLoginAttempt(email),
  cleanupExpiredSessions: (now) => storage.cleanupExpiredSessions(now),
});
